### ISSUE TITLE
sendKeys does not work correctly and only sends the last character!

### ISSUE THREAD

**Issue by mothaninja** [YOU-i-Labs/appium-youiengine-driver#115]
When using Appium for testing and calling the sendKeys command on an input field using YouiTV Engine 5.7.0, the command only sends the last character!

For example, if I do `sendKeys("helloworld")`, the command only sends "d" to the youitv text input ...

According to the documentation, this command should work in 5.0+ which it does but does not send all keys only the last character :(

**Comment by simongranger** [comment]
Is this using ReactNative Vanilla API?
That is unfortunately the behaviour with that API.
