### ISSUE TITLE
Not able to open app using appium-youiengine-driver

### ISSUE THREAD

**Issue by sp090** [YOU-i-Labs/appium-youiengine-driver#116]
When i try to open the application using appium-youiengine-driver with desired capability &
For apple tv 4k - 
{
  "app": "",
  "automationName": "YouiEngine",
  "deviceName": "",
  "platformName": "",
  "udid": "",
  "youiEngineAppAddress": ""
}

Please help me out

**Comment by simongranger** [comment]
Unfortunately, for AppleTV 4k there is no way to launch the app over wifi. For 4k, you must use the simulator.

You must fill in the capabilities for your platform, by entering:
"app": "<Path to your app>",
"automationName": "YouiEngine",
"deviceName": "<A device name for log purpose>",
"platformName": "yitivos",
"udid": "<devices udid>",
"youiEngineAppAddress": "localhost"

Details for each platform can be found here:
https://github.com/YOU-i-Labs/appium-youiengine-driver#youi-tvos

**Comment by sp090** [comment]
Thank you. 

> Unfortunately, for AppleTV 4k there is no way to launch the app over wifi. For 4k, you must use the simulator.
> 
> You must fill in the capabilities for your platform, by entering:
> "app": "",
> "automationName": "YouiEngine",
> "deviceName": "", "platformName": "yitivos", "udid": "", "youiEngineAppAddress": "localhost"
> 
> Details for each platform can be found here: https://github.com/YOU-i-Labs/appium-youiengine-driver#youi-tvos

**Comment by swadhinacharya-gl** [comment]
When i try to open the application using appium-youiengine-driver with desired capability &
For roku apps-
{
"app": "",
"automationName": "YouiEngine",
"deviceName": "",
"platformName": "YIRoku",
"youiEngineAppAddress": ""
}

I am also getting the YIRoku is not a supportive platformName 

i am following bellow given article to launch ROKU apps.
https://www.npmjs.com/package/appium-youiengine-driver/v/1.1.0

**Comment by simongranger** [comment]
please see
