### ISSUE TITLE
Please provide detail for LG web os Tv & Roku TV desired capability 

### ISSUE THREAD

**Issue by sp090** [YOU-i-Labs/appium-youiengine-driver#123]
Hello 

Please provide desired capability example for LG web os Tv & Roku TV

**Comment by simongranger** [comment]
https://github.com/YOU-i-Labs/appium-youiengine-driver#connect-to-app

Roku TV is not supported

**Comment by lukeyoui** [comment]
Closing this issue as ConnectToApp is the current method for connecting to LG. Feel free to create a new issue if you have other concerns.
