### ISSUE TITLE
Why are we making extra validation of "app" caps in this driver explicitely

### ISSUE THREAD

**Issue by rishav-csenitjsr** [YOU-i-Labs/appium-youiengine-driver#127]
For more ref: https://github.com/YOU-i-Labs/appium-youiengine-driver/blob/master/lib/driver.js#L236
We are making extra validation by checking `caps.app`. I think it is not required as one can manually install their app and launch it using `appPackage` and `appActivity` cap. In this case, `app` cap is not required. If it's not required, then I can create a PR to remove this. @simongranger

**Comment by simongranger** [comment]
It is expected that the proxied driver appium-android-driver and appium-xcuitest-driver launch the app on creation of the session. Same goes for platforms we do not proxy. To connect to an already launched app you can use `platform = connectToApp`.
Does this answer you questions?

**Comment by rishav-csenitjsr** [comment]
But there are different ways of launching the apps in the creating of the session, right ? So why are we validating with “app” cap only.

**Comment by lukeyoui** [comment]
Hey @rishav-csenitjsr!
 I'm revisiting old issues to clean up the repo. I am going to close this issue for now, but if you feel it can be addressed in a PR or requires another issue feel free to open one.
