### ISSUE TITLE
can't run session on Android 11 with automationName: YouIEngine 

### ISSUE THREAD

**Issue by swaraliRaut** [YOU-i-Labs/appium-youiengine-driver#134]
## The problem

Cant run session on android 11 with youiengine driver.
Appium createSession request errors on Android 11, for AutomationName "youiengine".

## Environment

* Appium version (or git revision) that exhibits the issue: 1.17.0/ 1.16.0
* Last Appium version that did not exhibit the issue (if applicable): NA
* Desktop OS/version used to run Appium: MacOs Catalina
* Node.js version (unless using Appium.app|exe): 13/18
* Npm or Yarn package manager:
* Mobile platform/version under test: Android 11
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe:
* You.i Engine Version: YouiEngineDriver (v1.2.3)

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs
cant include full appium logs for security reasons.
Snippet after which session terminates:
`[debug] [UiAutomator] Starting UIAutomator
  [debug] [ADB] Creating ADB subprocess with args: ["-P",5037,"-s","99151FFAZ00E8E","shell","uiautomator","runtest","AppiumBootstrap.jar","-c","io.appium.android.bootstrap.Bootstrap","-e","pkg","packagename","-e","disableAndroidWatchers",false,"-e","acceptSslCerts",false]
[UiAutomator] UiAutomator exited unexpectedly with code 0, signal null
[debug] [UiAutomator] Moving to state 'stopped'
Unhandled rejection Error: UiAUtomator shut down unexpectedly`

## Code To Reproduce Issue [ Good To Have ]
Just start the session with automationName YouIengine, for a device running on Android 11

**Comment by lukeyoui** [comment]
Hi @swaraliRaut, do you see this issue with Appium server version 1.18 as well? You have only encountered this on Android 11, correct?

**Comment by swaraliRaut** [comment]
hey @lukeyoui 
yes, I see this issue with Appium server version 1.18 as well
and also only see this error only on android 11.

**Comment by lukeyoui** [comment]
Thanks @swaraliRaut. I have been able to reproduce the issue. 

The UIAutomator has been officially deprecated and will not function with Android 11, so we will need to upgrade to UIAutomator2. I will keep you posted when the upgrade had been implemented and tested.

**Comment by simongranger** [comment]
We have changed our driver to use UIAutomator2 and that fixed the issue.
Expect to see the change in the next Appium release.
