### ISSUE TITLE
Mobile (Android, iOS): handle redirect to web-browser (other apps)

### ISSUE THREAD

**Issue by daroshchanka** [YOU-i-Labs/appium-youiengine-driver#141]
In my case the **youiengine** app contains an external sign-in step, when the user redirected to some web page with login/password fields and switched back to the app after sign-in completed. E. g. for iOS mobile Safari browser opens and YouiEngineDriver is not able even to `getPageSource`.

```
[HTTP] --> GET /wd/hub/session/e667a76f-d40d-459d-8aaf-9287f268f994/source
[HTTP] {}
[debug] [MJSONWP (e667a76f)] Calling AppiumDriver.getPageSource() with args: ["e667a76f-d40d-459d-8aaf-9287f268f994"]
[debug] [YouiEngineDriver] Executing YouiEngine WebDriver command 'getPageSource'
[debug] [YouiEngineDriver] COMMAND: {"name":"GetSRC"}
[YouiEngineDriver] Timeout in execute command.
[YouiEngineDriver] Socket failed. Retrying: 1
[debug] [YouiEngineDriver] COMMAND: {"name":"GetSRC"}
[YouiEngineDriver] Timeout in execute command.
[YouiEngineDriver] Socket failed. Retrying: 2
[debug] [YouiEngineDriver] COMMAND: {"name":"GetSRC"}
[YouiEngineDriver] Timeout in execute command.
[YouiEngineDriver] Socket failed. Retrying: 3
[debug] [MJSONWP (e667a76f)] Encountered internal error running command: Error: ExecuteSocketCommand failed.
[debug] [MJSONWP (e667a76f)]     at YouiEngineDriver.executeSocketCommand (/usr/local/lib/node_modules/appium/node_modules/appium-youiengine-driver/lib/driver.js:507:11)
[debug] [MJSONWP (e667a76f)]     at YouiEngineDriver.commands.getPageSource (/usr/local/lib/node_modules/appium/node_modules/appium-youiengine-driver/lib/commands/general.js:48:12)
[HTTP] <-- GET /wd/hub/session/e667a76f-d40d-459d-8aaf-9287f268f994/source 500 30015 ms - 199

```

But other Appium drivers (uiautomator2, xcuitest) work with this perfectly.

It would be great somehow to have 2 active drivers in a time (e. g. youiengine and xcuitest) and switch context, in order to perform some actions outside of youi-app.

**Comment by daroshchanka** [comment]
As a temporary workaround, I've launch `xcuitest` Appium session and YouiEngineDriver with `ConnectToApp` platformName.

So I need to keep two active Appium sessions per device in my tests to make it work.

**Comment by lukeyoui** [comment]
Hey @daroshchanka. Are you still seeing this issue? I've revisiting old issues to clean up the log, but I am wondering if this one was fixed with the YOUI_APP context change.

**Comment by daroshchanka** [comment]
Hi @lukeyoui, unfortunatelly I have no ability to recheck it any more (test app behavior changed).

But it looks like it should work with #143.

So it's ok to close this issue for now.

**Comment by lukeyoui** [comment]
Thanks for letting me know!

**Comment by scmfz** [comment]
I keep running in the same issue but not for the same reason:

[YouiEngineDriver] Timeout in execute command.
[YouiEngineDriver] Socket failed. Retrying: 1
[YouiEngineDriver] COMMAND: {"name":"setSourceTreeFilter","args":["[@isDisplayed='true']"]}
[YouiEngineDriver] Timeout in execute command.
[YouiEngineDriver] Socket failed. Retrying: 2
[YouiEngineDriver] COMMAND: {"name":"setSourceTreeFilter","args":["[@isDisplayed='true']"]}
[iProxy@00008030:8100] The connection has been closed
[YouiEngineDriver] Timeout in execute command.
[YouiEngineDriver] Socket failed. Retrying: 3
[YouiEngineDriver] Deleting YouiEngine session

On the latest version - is there a reason for this happening?
