### ISSUE TITLE
Command line args passed while starting Appium are not honoured while creating youiengine driver 

### ISSUE THREAD

**Issue by swaraliRaut** [YOU-i-Labs/appium-youiengine-driver#144]
## The problem

I am passing `--webdriveragent-port` option while starting appium, which gets honoured as wdaLocalPort cap in Appium session.
But in case of YouIEngineDriver, only `javascriptEnabled: true,` is passed in args, and default options are not passed while creating xcuitest driver, resulting in WDA starting on the default port.

We should start passing `this.opts` along with args [here](https://github.com/YOU-i-Labs/appium-youiengine-driver/blob/master/lib/driver.js#L265), to honor default arguments passed to appium.

## Environment

* Appium version (or git revision) that exhibits the issue: all
* Last Appium version that did not exhibit the issue (if applicable): NA
* Desktop OS/version used to run Appium: MAC OS 10.14
* Node.js version (unless using Appium.app|exe): NA
* Npm or Yarn package manager:  NA
* Mobile platform/version under test: NA
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium.app
* You.i Engine Version: All

**Comment by ervinding** [comment]
Closing since #145  was merged
