### ISSUE TITLE
appium-youiengine-driver download issue with latest version.

### ISSUE THREAD

**Issue by mohanrajmcad** [YOU-i-Labs/appium-youiengine-driver#65]
I am not facing any issues while installing appium 1.7.1 due to dependency with appium-youienging-driver 1.0.13. I am able to download the file from https://registry.npmjs.org/appium-youiengine-driver/-/appium-youiengine-driver-1.0.13.tgz as well. However I am unable to download https://registry.npmjs.org/appium-youiengine-driver/-/appium-youiengine-driver-1.0.14.tgz behind the corporate firewall and mcafee says invalid archive. Could you please check if 1.0.14 contains any suspicious file. Due to this I am unable to install appium 1.7.2 now :(

**Comment by simongranger** [comment]
Hello,
We have not seen any issues downloading Appium 1.7.2 or appium-youiengine-driver 1.0.14.
Can you try installing it with 'npm install appium-youiengine-driver' to see if that works?

**Comment by mohanrajmcad** [comment]
I have tried, bit failures as below.

npm ERR! fetch failed http://registry.npmjs.org/appium-youiengine-driver/-/appium-youiengine-driver-1.0.14.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 403
npm ERR! fetch failed http://registry.npmjs.org/appium-youiengine-driver/-/appium-youiengine-driver-1.0.14.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 403
npm ERR! fetch failed http://registry.npmjs.org/appium-youiengine-driver/-/appium-youiengine-driver-1.0.14.tgz
npm ERR! fetch failed with status code 403

However "npm install appium-youiengine-driver@1.0.13" works fine. So issues with latest version... :(

**Comment by simongranger** [comment]
Hello again, 
can you try looking at this: 
https://stackoverflow.com/questions/39296271/error-fetch-failed-with-status-code-403

**Comment by mohanrajmcad** [comment]
Corporate IT process to whiltelisting url is time taking process here,  do you have any plans to release next version nearby?

**Comment by TamimiGitHub** [comment]
Hey @mohanrajmcad, I have downloaded 1.0.13 and 1.0.14 in separate directories  as follows
`npm install appium-youi-driver@1.0.14` and `npm install appium-youi-driver@1.0.13`. Diffing the two packages (`diff -rq 1.0.14 1.0.13 > diff_14_13.txt`) shows that there are only 4 files the differ which are 
```
driver.js
desired-caps.js
package.json
package-lock.json
```
Any updates from your end on the status of downloading?

**Comment by mohanrajmcad** [comment]
@TamimiGitHub

No issues with 1.0.13, but getting the message below for 1.0.14.

This file is blocked, because its detected type is not supported by archive handler.
URL: https://registry.npmjs.org/appium-youiengine-driver/-/appium-youiengine-driver-1.0.14.tgz
Filename: appium-youiengine-driver-1.0.13.tgz
Media Type (detected): application/x-tar

I am not sure about file names conflict. Is it required to zip again from owner?

**Comment by TamimiGitHub** [comment]
@mohanrajmcad What OS are you downloading this on? is it a MAC/Windows/Linux machine?

**Comment by mohanrajmcad** [comment]
@TamimiGitHub,

MacOS - chrome browser
