### ISSUE TITLE
Usage with Consoles (PS4 and XBox One)

### ISSUE THREAD

**Issue by goodbomb** [YOU-i-Labs/appium-youiengine-driver#86]
Hi, the dev team I'm working with is looking at using the You.i engine for developing some apps on Consoles. Does this driver work on the consoles as well, and if so, is there any documentation to explain how to use Appium with Console apps?

Thanks.

**Comment by simongranger** [comment]
Hi Ben, we have validated we could also run on PS4, Tizen, Windows and Linux as well. We have not gotten to add installer in the driver but that should not be a big deal to add.
XBox One had issues with the socket but that could be looked into if you make a request.

**Comment by goodbomb** [comment]
Okay, thanks @simongranger. We will definitely need XBox One support as well if we decide to move forward with You.i. I'll keep you posted when/if we need to start onboarding with your tech.

**Comment by matthew-dean** [comment]
@simongranger Can PS4 / Linux / Xbox documentation be added here -> https://github.com/YOU-i-Labs/appium-youiengine-driver#minimum-required-capabilities-per-platform

**Comment by simongranger** [comment]
We haven't added the install/launch/close/remove methods for those platforms yet, but considering you launch the app yourself, you can run scripts with the following caps using "noproxy" as platformName:
[caps]
app = "dummy"
automationName = "YouiEngine"
deviceName = "myDevice"
platformName = "noproxy"
youiEngineAppAddress = "<Device's IP Address>"

**Comment by mohammadarif87** [comment]
@simongranger Sorry to bring this back up after you've closed it. Do you know if I can connect the appium inspector to Xbox One? I've tried using the capabilities you've mentioned with platformName set as noproxy, appium inspector says failed to connect after attempting 3 times.

**Comment by lukeyoui** [comment]
Hi @mohammadarif87 
I believe Xbox One is not support by the driver.
That being said, you can try with:
 platformName = "ConnectToApp"  instead of "noproxy".
 If that doesn't work, it may be related to the level of support of the webdriver socket on xbox.
